RABSW-1003: Use ResourceError for NnfNodeStorage and ClientMount (#50)
* RABSW-1003: Use ResourceError for NnfNodeStorage and ClientMount

This commit uses the new ResourceError struct from DWS to return extra
error information from the NnfNodeStorage and ClientMount controllers.

This error information is used in the workflow resource. For example, an allocation
request that was too large would result in an error in the workflow:

  drivers:
  ...
  - completed: false
    driverID: nnf
    dwdIndex: 0
    error: 'Could not create StoragePool: Error 406: Not Acceptable, Cause: Insufficient
      capacity available, Internal Error: Insufficient capacity available. Requested:
      0x1c6bf52634000 Available: 0x200000000000'
    lastHB: 0
    message: Insufficient capacity available
    status: Error
    taskID: ""
    watchState: setup
  message: 'DW Directive 0: Insufficient capacity available'
  ready: false
  state: setup
  status: Error

Signed-off-by: Matt Richerson <mattr@cray.com>

* Re-vendor DWS. Don't use Get/Set

Signed-off-by: Matt Richerson <mattr@cray.com>

* re-vendor

Signed-off-by: Matt Richerson <mattr@cray.com>

Signed-off-by: Matt Richerson <mattr@cray.com>
Co-authored-by: Matt Richerson <mattr@cray.com>